# Generated by Django 5.1.7 on 2025-04-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_discoteca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('IBAN', models.CharField(max_length=100)),
                ('moneda', models.CharField(choices=[('EU', 'Euro'), ('DOL', 'Dolar'), ('LIB', 'Libra')], default='EU', max_length=3)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente')),
            ],
        ),
    ]
