# Generated by Django 5.1.7 on 2025-04-22 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('facturacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.vendedor')),
            ],
        ),
    ]
