# Generated by Django 5.1.7 on 2025-04-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_datosvendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoteca',
            name='vendedor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.vendedor'),
        ),
    ]
