# Generated by Django 5.1.7 on 2025-04-24 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_discoteca_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('discoteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.discoteca')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.entrada')),
            ],
        ),
        migrations.AddField(
            model_name='discoteca',
            name='entrada',
            field=models.ManyToManyField(through='tienda.Inventario', to='tienda.entrada'),
        ),
    ]
