# Generated by Django 5.1.7 on 2025-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_pedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='precio',
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
