# Generated by Django 5.1.7 on 2025-05-15 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_entrada_precio_inventario_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='entrada',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='inventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.inventario'),
            preserve_default=False,
        ),
    ]
